/**
 * site-generator — Generates a self-contained Next.js app from a blueprint.
 *
 * Output: output/generated-site/
 * Components are copied from site-template/; pages are generated with real data embedded.
 * After generation, run `next build` inside output/generated-site/ to produce
 * static HTML in output/generated-site/out/, then copy to output/static-site/.
 */

import * as fs from "fs";
import * as path from "path";
import type { WebsiteBlueprint, BusinessData } from "../schemas/blueprint.types.js";

export interface GeneratorResult {
  ok: boolean;
  generatedDir: string;
  filesWritten: number;
  warnings: string[];
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export function generateSite(blueprint: WebsiteBlueprint, projectRoot: string): GeneratorResult {
  const generatedDir = path.join(projectRoot, "output", "generated-site");
  const templateDir = path.join(projectRoot, "site-template");
  const warnings: string[] = [];
  let filesWritten = 0;

  const write = (rel: string, content: string) => {
    fs.mkdirSync(path.dirname(path.join(generatedDir, rel)), { recursive: true });
    fs.writeFileSync(path.join(generatedDir, rel), content, "utf-8");
    filesWritten++;
  };

  const copyFile = (fromRel: string, toRel: string) => {
    const src = path.join(templateDir, fromRel);
    const dst = path.join(generatedDir, toRel);
    if (fs.existsSync(src)) {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.copyFileSync(src, dst);
      filesWritten++;
    } else {
      warnings.push(`Template file not found: ${fromRel}`);
    }
  };

  // ── Directory scaffold ──────────────────────────────────────────────────────
  fs.mkdirSync(generatedDir, { recursive: true });

  // ── Package config ──────────────────────────────────────────────────────────
  write("package.json", JSON.stringify({ name: "generated-site", version: "1.0.0", private: true }, null, 2));

  write("next.config.js", `/** @type {import('next').NextConfig} */
const nextConfig = { output: "export", trailingSlash: true, images: { unoptimized: true } };
module.exports = nextConfig;
`);

  write("tsconfig.json", JSON.stringify({
    compilerOptions: {
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true, skipLibCheck: true, strict: true, noEmit: true,
      esModuleInterop: true, module: "esnext", moduleResolution: "bundler",
      resolveJsonModule: true, isolatedModules: true, jsx: "preserve",
      incremental: true, plugins: [{ name: "next" }], paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2));

  // ── Copy components and lib from site-template ──────────────────────────────
  const componentDir = path.join(templateDir, "components");
  if (fs.existsSync(componentDir)) {
    for (const file of fs.readdirSync(componentDir)) {
      copyFile(`components/${file}`, `components/${file}`);
    }
  }
  copyFile("lib/types.ts", "lib/types.ts");

  // ── Shared site config (data module, imported by all pages) ─────────────────
  write("site.config.ts", generateSiteConfig(blueprint));

  // ── CSS with real brand colors and fonts ─────────────────────────────────────
  write("app/globals.css", generateGlobalsCss(blueprint));

  // ── Root layout with JSON-LD, fonts, and site-wide metadata ─────────────────
  write("app/layout.tsx", generateLayout(blueprint));

  // ── Page files (one per route) ───────────────────────────────────────────────
  for (const route of blueprint.frontend.routes) {
    const content = generatePage(route.pageId, route.path, blueprint);
    write(route.file, content);
  }

  // ── Public assets ────────────────────────────────────────────────────────────
  write("public/robots.txt", generateRobotsTxt());
  write("public/sitemap.xml", generateSitemapXml(blueprint));

  // Gallery images use picsum.photos for realistic layout previews.
  // Seeds are deterministic: same seed = same photo on every build.
  // Replace these URLs with real photos before going live.

  return { ok: true, generatedDir, filesWritten, warnings };
}

// ─── site.config.ts — shared data module ─────────────────────────────────────

function generateSiteConfig(bp: WebsiteBlueprint): string {
  const { business, ux } = bp;
  const hours = Object.entries(business.operatingHours).map(([days, h]) => ({ days, hours: h }));
  const services = buildServiceItems(business.services, business.industry);
  const galleryImages = buildGalleryImages(business);
  const bookingUrl = extractBookingUrl(business.booking);

  return `// Generated by Stitchfy v2 — do not edit manually
// Source: output/blueprint/website-blueprint.v1.json

import type { NavItem, ContactInfo, HoursEntry, ServiceItem, Testimonial, GalleryImage } from "@/lib/types";

export const businessName = ${JSON.stringify(business.name)};

export const tagline = ${JSON.stringify(business.description)};

export const navigation: NavItem[] = ${JSON.stringify(ux.navigation, null, 2)};

export const contact: ContactInfo = {
  phone: ${JSON.stringify(business.phone)},
  email: ${JSON.stringify(business.email)},
  address: ${JSON.stringify(business.address)},
};

export const hours: HoursEntry[] = ${JSON.stringify(hours, null, 2)};

export const social: Record<string, string> = ${JSON.stringify(business.socialLinks, null, 2)};

export const bookingUrl: string | null = ${JSON.stringify(bookingUrl)};

export const services: ServiceItem[] = ${JSON.stringify(services, null, 2)};

// Placeholder testimonials — replace with real client reviews
export const testimonials: Testimonial[] = [
  { quote: "The team here is absolutely amazing. I came in for a treatment and walked out feeling like a completely different person. Highly recommend!", author: "Sarah M." },
  { quote: "Best experience I've had in ${business.location}. The atmosphere is so relaxing and everyone is so talented. Will definitely be back!", author: "Jessica R." },
  { quote: "I've been a loyal client for over a year. Consistent quality every time. Love this place!", author: "Priya K." },
];

// Placeholder gallery images — replace src paths with real photos
export const galleryImages: GalleryImage[] = ${JSON.stringify(galleryImages, null, 2)};

export const galleryCategories: string[] = ["Hair", "Nails", "Skincare"];
`;
}

// ─── globals.css ──────────────────────────────────────────────────────────────

function generateGlobalsCss(bp: WebsiteBlueprint): string {
  const { colorPalette, typography } = bp.ux;
  return `/* Generated by Stitchfy v2 */
:root {
  --color-primary: ${colorPalette.primary};
  --color-secondary: ${colorPalette.secondary};
  --color-accent: ${colorPalette.accent};
  --color-text: ${colorPalette.text};
  --color-background: ${colorPalette.background};
  --color-border: ${colorPalette.border};
  --color-white: #FFFFFF;

  --font-heading: ${typography.headingFont};
  --font-body: ${typography.bodyFont};

  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 2rem;
  --spacing-xl: 4rem;

  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 24px;

  --max-width: 1200px;
  --section-padding: 4rem 1.5rem;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }

body {
  font-family: var(--font-body);
  color: var(--color-text);
  background-color: var(--color-background);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  font-size: ${typography.scaleBase};
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  font-weight: ${typography.headingWeight};
  line-height: 1.2;
}

a { color: var(--color-primary); text-decoration: none; }
a:hover { text-decoration: underline; }
img { max-width: 100%; height: auto; display: block; }

:focus-visible {
  outline: 3px solid var(--color-primary);
  outline-offset: 3px;
  border-radius: 2px;
}

.container {
  width: 100%;
  max-width: var(--max-width);
  margin: 0 auto;
  padding: 0 1.5rem;
}

.sr-only {
  position: absolute; width: 1px; height: 1px; padding: 0;
  margin: -1px; overflow: hidden; clip: rect(0,0,0,0);
  white-space: nowrap; border: 0;
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;
}

// ─── app/layout.tsx ───────────────────────────────────────────────────────────

function generateLayout(bp: WebsiteBlueprint): string {
  const { business, seo, ux } = bp;
  const jsonLd = buildJsonLd(business, ux);

  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: ${JSON.stringify(seo.siteTitle)},
    template: "%s | ${escapeTemplate(business.name)}",
  },
  description: ${JSON.stringify(seo.defaultMetaDescription)},
  openGraph: {
    type: "website",
    siteName: ${JSON.stringify(business.name)},
    title: ${JSON.stringify(seo.openGraph["og:title"] ?? seo.siteTitle)},
    description: ${JSON.stringify(seo.openGraph["og:description"] ?? seo.defaultMetaDescription)},
    images: [{ url: "/og-image.svg", width: 1200, height: 630 }],
  },
};

const jsonLd = ${JSON.stringify(jsonLd, null, 2)};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&family=Inter:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
`;
}

// ─── Page generators ──────────────────────────────────────────────────────────

function generatePage(pageId: string, pagePath: string, bp: WebsiteBlueprint): string {
  const generators: Record<string, () => string> = {
    "home": () => generateHomePage(bp),
    "services": () => generateServicesPage(bp),
    "gallery": () => generateGalleryPage(bp),
    "about-us": () => generateAboutPage(bp),
    "contact": () => generateContactPage(bp),
    "book-online": () => generateBookPage(bp),
  };

  return (generators[pageId] ?? (() => generateGenericPage(pageId, pagePath, bp)))();
}

function heroStyleToCssProps(heroStyle: WebsiteBlueprint["ux"]["heroStyle"]): Record<string, string> {
  if (heroStyle.backgroundType === "gradient" && heroStyle.gradientFrom && heroStyle.gradientTo) {
    return {
      background: `linear-gradient(135deg, ${heroStyle.gradientFrom} 0%, ${heroStyle.gradientTo} 100%)`,
      color: heroStyle.textColor,
    };
  }
  if (heroStyle.backgroundType === "solid" && heroStyle.backgroundColor) {
    return {
      backgroundColor: heroStyle.backgroundColor,
      color: heroStyle.textColor,
    };
  }
  // fallback — solid using gradientFrom or textColor inverse
  return { color: heroStyle.textColor };
}

function sharedImports(): string {
  return `import { AccessibilitySkipLink } from "@/components/AccessibilitySkipLink";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import {
  businessName, navigation, contact, hours, social, services,
  testimonials, galleryImages, galleryCategories, bookingUrl,
} from "@/site.config";`;
}

function headerJsx(bp: WebsiteBlueprint): string {
  const { header } = bp.ux;
  const bookingHref = extractBookingUrl(bp.business.booking) ?? `tel:${bp.business.phone.replace(/\D/g, "")}`;
  return `<Header
        businessName={businessName}
        navigation={navigation}
        showPhone={${header.showPhone}}
        phone={contact.phone}
        showCTA={${header.showCTA}}
        ctaLabel="${escapeTemplate(header.ctaLabel)}"
        ctaHref="${bookingHref}"
      />`;
}

function footerJsx(bp: WebsiteBlueprint): string {
  return `<Footer
        businessName={businessName}
        navigation={navigation}
        contact={contact}
        social={social}
        hours={hours}
        legalNote="${escapeTemplate(bp.ux.footer.legalNote)}"
      />`;
}

function generateHomePage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "home");
  const homePage = bp.pages.find((p) => p.id === "home");
  const bookingUrl = extractBookingUrl(bp.business.booking) ?? `/contact`;
  const heroBgStyle = heroStyleToCssProps(bp.ux.heroStyle);

  return `import type { Metadata } from "next";
${sharedImports()}
import { Hero } from "@/components/Hero";
import { ServicesGrid } from "@/components/ServicesGrid";
import { TestimonialsSection } from "@/components/TestimonialsSection";
import { GallerySection } from "@/components/GallerySection";
import { BookingCTA } from "@/components/BookingCTA";
import { HoursBlock } from "@/components/HoursBlock";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? bp.seo.siteTitle)},
  description: ${JSON.stringify(meta?.description ?? bp.seo.defaultMetaDescription)},
  alternates: { canonical: "/" },
};

export default function HomePage() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <Hero
          content={{
            headline: ${JSON.stringify(`${bp.business.name} — ${bp.business.industry} in ${bp.business.location}`)},
            subheadline: ${JSON.stringify(bp.business.description)},
            primaryCta: ${JSON.stringify(homePage?.primaryCTA ?? { label: "Book Now", href: "/book" })},
            secondaryCta: ${JSON.stringify(homePage?.secondaryCTA ?? { label: "Our Services", href: "/services" })},
          }}
          backgroundStyle={${JSON.stringify(heroBgStyle)}}
        />
        <ServicesGrid
          services={services.slice(0, 6)}
          heading="Our Services"
        />
        <TestimonialsSection testimonials={testimonials} />
        <GallerySection
          images={galleryImages.slice(0, 6)}
          heading="Our Work"
          categories={galleryCategories}
          filterable={false}
        />
        <BookingCTA
          headline="Ready to Look and Feel Your Best?"
          subheadline="Book your appointment online — it only takes a minute."
          cta={{ label: "Book Appointment", href: ${JSON.stringify(bookingUrl)} }}
        />
        <HoursBlock hours={hours} heading="Our Hours" />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateServicesPage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "services");
  const bookingUrl = extractBookingUrl(bp.business.booking) ?? `/contact`;

  return `import type { Metadata } from "next";
${sharedImports()}
import { ServicesGrid } from "@/components/ServicesGrid";
import { BookingCTA } from "@/components/BookingCTA";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `Services | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? `All services at ${bp.business.name}.`)},
  alternates: { canonical: "/services" },
};

export default function ServicesPage() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <section style={{ padding: "3rem 1.5rem 1rem" }}>
          <div className="container">
            <h1 style={{ fontFamily: "var(--font-heading)", fontSize: "clamp(2rem, 5vw, 3rem)", marginBottom: "0.5rem" }}>
              Our Services
            </h1>
            <p style={{ color: "var(--color-text)", opacity: 0.7, fontSize: "1.1rem" }}>
              Professional ${bp.business.industry} services in ${bp.business.location}.
            </p>
          </div>
        </section>
        <ServicesGrid services={services} heading="" />
        <BookingCTA
          headline="Ready to Book a Service?"
          subheadline="Walk-ins welcome. Appointments recommended on weekends."
          cta={{ label: "Book Now", href: ${JSON.stringify(bookingUrl)} }}
        />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateGalleryPage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "gallery");

  return `import type { Metadata } from "next";
${sharedImports()}
import { GallerySection } from "@/components/GallerySection";
import { BookingCTA } from "@/components/BookingCTA";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `Gallery | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? `Browse our work at ${bp.business.name}.`)},
  alternates: { canonical: "/gallery" },
};

export default function GalleryPage() {
  const bookingHref = bookingUrl ?? "/contact";
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <section style={{ padding: "3rem 1.5rem 1rem" }}>
          <div className="container">
            <h1 style={{ fontFamily: "var(--font-heading)", fontSize: "clamp(2rem, 5vw, 3rem)", marginBottom: "0.5rem" }}>
              Our Work
            </h1>
            <p style={{ color: "var(--color-text)", opacity: 0.7, fontSize: "1.1rem" }}>
              Browse before-and-after photos and finished results from ${bp.business.name}.
            </p>
          </div>
        </section>
        <GallerySection
          images={galleryImages}
          heading=""
          categories={galleryCategories}
          filterable={true}
        />
        <BookingCTA
          headline="Like What You See?"
          subheadline="Book your appointment and let us create your look."
          cta={{ label: "Book Now", href: bookingHref }}
        />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateAboutPage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "about-us");
  const heroBgStyle = heroStyleToCssProps(bp.ux.heroStyle);

  return `import type { Metadata } from "next";
${sharedImports()}
import { Hero } from "@/components/Hero";
import { ServicesGrid } from "@/components/ServicesGrid";
import { TestimonialsSection } from "@/components/TestimonialsSection";
import { CTASection } from "@/components/CTASection";
import { ContactSection } from "@/components/ContactSection";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `About Us | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? `Learn about the team at ${bp.business.name}.`)},
  alternates: { canonical: "/about" },
};

export default function AboutPage() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <Hero
          content={{
            headline: ${JSON.stringify(`About ${bp.business.name}`)},
            subheadline: ${JSON.stringify(bp.business.description)},
            primaryCta: { label: "Our Services", href: "/services" },
            secondaryCta: { label: "Contact Us", href: "/contact" },
          }}
          backgroundStyle={${JSON.stringify(heroBgStyle)}}
        />
        <ServicesGrid services={services.slice(0, 4)} heading="What We Offer" />
        <TestimonialsSection testimonials={testimonials} />
        <CTASection
          headline="Ready to Experience ${escapeTemplate(bp.business.name)}?"
          subheadline="Visit us in ${escapeTemplate(bp.business.location)} or book online today."
          cta={{ label: "Contact Us", href: "/contact" }}
        />
        <ContactSection contact={contact} heading="Find Us" />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateContactPage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "contact");

  return `import type { Metadata } from "next";
${sharedImports()}
import { ContactSection } from "@/components/ContactSection";
import { HoursBlock } from "@/components/HoursBlock";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `Contact | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? `Get in touch with ${bp.business.name}.`)},
  alternates: { canonical: "/contact" },
};

export default function ContactPage() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <section style={{ padding: "3rem 1.5rem 1rem" }}>
          <div className="container">
            <h1 style={{ fontFamily: "var(--font-heading)", fontSize: "clamp(2rem, 5vw, 3rem)", marginBottom: "0.5rem" }}>
              Contact Us
            </h1>
            <p style={{ color: "var(--color-text)", opacity: 0.7, fontSize: "1.1rem" }}>
              ${escapeTemplate(bp.business.name)} — ${escapeTemplate(bp.business.location)}
            </p>
          </div>
        </section>
        <ContactSection contact={contact} heading="Get in Touch" />
        <HoursBlock hours={hours} heading="Our Hours" />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateBookPage(bp: WebsiteBlueprint): string {
  const meta = bp.seo.pageMeta.find((m) => m.pageId === "book-online");
  const externalUrl = extractBookingUrl(bp.business.booking);
  const bookingDisplay = externalUrl
    ? `<a
          href={${JSON.stringify(externalUrl)}}
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: "inline-flex", alignItems: "center",
            backgroundColor: "var(--color-primary)", color: "#fff",
            padding: "1rem 2.5rem", borderRadius: "var(--radius-md)",
            fontWeight: 700, fontSize: "1.1rem", textDecoration: "none",
            minHeight: "44px",
          }}
        >
          Book on Vagaro ↗
        </a>`
    : `<a
          href={\`tel:\${contact.phone?.replace(/\\D/g, "")}\`}
          style={{
            display: "inline-flex", alignItems: "center",
            backgroundColor: "var(--color-primary)", color: "#fff",
            padding: "1rem 2.5rem", borderRadius: "var(--radius-md)",
            fontWeight: 700, fontSize: "1.1rem", textDecoration: "none",
            minHeight: "44px",
          }}
        >
          Call to Book
        </a>`;

  return `import type { Metadata } from "next";
${sharedImports()}
import { ContactSection } from "@/components/ContactSection";

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `Book Online | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? `Book your appointment at ${bp.business.name}.`)},
  alternates: { canonical: "/book" },
};

export default function BookPage() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <section
          aria-labelledby="book-heading"
          style={{
            padding: "5rem 1.5rem",
            backgroundColor: "var(--color-secondary)",
            textAlign: "center",
          }}
        >
          <div className="container" style={{ maxWidth: "640px", margin: "0 auto" }}>
            <h1
              id="book-heading"
              style={{
                fontFamily: "var(--font-heading)",
                fontSize: "clamp(2rem, 5vw, 3rem)",
                marginBottom: "1rem",
              }}
            >
              Book Your Appointment
            </h1>
            <p style={{ fontSize: "1.1rem", opacity: 0.75, marginBottom: "2rem", lineHeight: 1.6 }}>
              ${escapeTemplate(bp.business.booking.split(";")[0] ?? "Walk-ins welcome.")}
            </p>
            ${bookingDisplay}
            <p style={{ marginTop: "1.5rem", fontSize: "0.9rem", opacity: 0.6 }}>
              You will be redirected to our booking platform. No account required.
            </p>
          </div>
        </section>
        <ContactSection contact={contact} heading="Questions? Contact Us" />
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

function generateGenericPage(pageId: string, pagePath: string, bp: WebsiteBlueprint): string {
  const page = bp.pages.find((p) => p.id === pageId);
  const meta = bp.seo.pageMeta.find((m) => m.pageId === pageId);
  const title = page?.title ?? pageId;

  return `import type { Metadata } from "next";
${sharedImports()}

export const metadata: Metadata = {
  title: ${JSON.stringify(meta?.title ?? `${title} | ${bp.business.name}`)},
  description: ${JSON.stringify(meta?.description ?? bp.seo.defaultMetaDescription)},
  alternates: { canonical: ${JSON.stringify(pagePath)} },
};

export default function ${toPascalCase(pageId)}Page() {
  return (
    <>
      <AccessibilitySkipLink />
      ${headerJsx(bp)}
      <main id="main-content">
        <section style={{ padding: "4rem 1.5rem" }}>
          <div className="container">
            <h1 style={{ fontFamily: "var(--font-heading)", fontSize: "clamp(2rem, 5vw, 3rem)", marginBottom: "1rem" }}>
              ${escapeTemplate(title)}
            </h1>
            <p style={{ opacity: 0.7 }}>${escapeTemplate(page?.purpose ?? "")}</p>
          </div>
        </section>
      </main>
      ${footerJsx(bp)}
    </>
  );
}
`;
}

// ─── Public asset generators ──────────────────────────────────────────────────

function generateRobotsTxt(): string {
  return `User-agent: *
Allow: /

Sitemap: /sitemap.xml
`;
}

function generateSitemapXml(bp: WebsiteBlueprint): string {
  const today = new Date().toISOString().split("T")[0];
  const urls = bp.pages
    .map((p) => `  <url><loc>${p.path}</loc><lastmod>${today}</lastmod><priority>${p.path === "/" ? "1.0" : "0.8"}</priority></url>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

// ─── Data helpers ─────────────────────────────────────────────────────────────

function extractBookingUrl(bookingText: string): string | null {
  const match = bookingText.match(/https?:\/\/[^\s;)\]]+/);
  return match ? match[0] : null;
}

const SERVICE_DESCRIPTIONS: Record<string, string> = {
  "Haircuts & Styling": "Precision cuts tailored to your face shape and lifestyle. Includes shampoo and blowout.",
  "Color & Balayage": "Expert color services from full color to sun-kissed balayage highlights.",
  "Blowouts & Deep Treatments": "Salon-quality blowout with moisture-infusing treatments for healthy, shiny hair.",
  "Manicure & Pedicure": "Classic and gel manicures and pedicures with professional-grade products.",
  "Gel & Acrylic Nails": "Long-lasting gel and acrylic nail enhancements with customizable designs.",
  "Facials & Skincare Treatments": "Customized facials targeting your specific skin concerns and goals.",
  "Eyebrow Shaping & Tinting": "Brow shaping, threading, and tinting to frame your face beautifully.",
  "Lash Extensions": "Volume and classic lash extensions for a dramatic or natural look.",
};

function buildServiceItems(services: string[], industry: string): Array<{ name: string; description: string }> {
  return services.map((name) => ({
    name,
    description: SERVICE_DESCRIPTIONS[name] ?? `Professional ${name.toLowerCase()} from our experienced team.`,
  }));
}

// picsum.photos seed format: https://picsum.photos/seed/{seed}/800/600
// Seeds are stable strings → same photo every build. Replace with real photos before launch.
const PICSUM_BASE = "https://picsum.photos/seed";

const GALLERY_TEMPLATES: Record<string, Array<{ seed: string; alt: string; category: string }>> = {
  beauty: [
    { seed: "luxe-hair-a", alt: "Haircut and styling — precision cut with blowout finish", category: "Hair" },
    { seed: "luxe-hair-b", alt: "Balayage color treatment — golden highlights on brunette hair", category: "Hair" },
    { seed: "luxe-nails-a", alt: "Gel manicure in rose pink — polished finish", category: "Nails" },
    { seed: "luxe-nails-b", alt: "Acrylic nail extensions with custom nail art design", category: "Nails" },
    { seed: "luxe-skin-a", alt: "Relaxing facial skincare treatment in progress", category: "Skincare" },
    { seed: "luxe-lash-a", alt: "Lash extension application — natural volume lashes", category: "Skincare" },
  ],
  wellness: [
    { seed: "wellness-massage-a", alt: "Deep tissue massage treatment session", category: "Massage" },
    { seed: "wellness-yoga-a", alt: "Yoga and mindfulness studio space", category: "Classes" },
    { seed: "wellness-facial-a", alt: "Rejuvenating facial treatment", category: "Skincare" },
    { seed: "wellness-spa-a", alt: "Relaxation spa environment", category: "Spa" },
    { seed: "wellness-body-a", alt: "Body wrap and detox treatment", category: "Body" },
    { seed: "wellness-med-a", alt: "Wellness consultation and care", category: "Consultation" },
  ],
  restaurant: [
    { seed: "resto-food-a", alt: "Chef's signature dish — beautifully plated", category: "Food" },
    { seed: "resto-food-b", alt: "Fresh seasonal ingredients", category: "Food" },
    { seed: "resto-drink-a", alt: "Handcrafted cocktail selection", category: "Drinks" },
    { seed: "resto-interior-a", alt: "Restaurant dining room ambiance", category: "Ambiance" },
    { seed: "resto-food-c", alt: "Dessert selection — homemade pastries", category: "Food" },
    { seed: "resto-bar-a", alt: "Bar area with curated wine list", category: "Drinks" },
  ],
  medical: [
    { seed: "med-clinic-a", alt: "Modern clinic reception and waiting area", category: "Facility" },
    { seed: "med-consult-a", alt: "Patient consultation room", category: "Facility" },
    { seed: "med-team-a", alt: "Medical team and care professionals", category: "Team" },
    { seed: "med-equip-a", alt: "State-of-the-art medical equipment", category: "Technology" },
    { seed: "med-care-a", alt: "Patient care and treatment in progress", category: "Care" },
    { seed: "med-lab-a", alt: "Laboratory and diagnostic services", category: "Technology" },
  ],
  default: [
    { seed: "biz-service-a", alt: "Professional service delivery", category: "Services" },
    { seed: "biz-team-a", alt: "Our dedicated team at work", category: "Team" },
    { seed: "biz-space-a", alt: "Our welcoming location", category: "Facility" },
    { seed: "biz-result-a", alt: "Outstanding results for our clients", category: "Work" },
    { seed: "biz-service-b", alt: "Quality and attention to detail", category: "Services" },
    { seed: "biz-client-a", alt: "Happy clients — our greatest reward", category: "Work" },
  ],
};

function buildGalleryImages(business: BusinessData): Array<{ src: string; alt: string; category?: string }> {
  const industry = business.industry.toLowerCase();
  let key: keyof typeof GALLERY_TEMPLATES = "default";
  if (/beauty|salon|hair|nail|lash|spa/.test(industry)) key = "beauty";
  else if (/wellness|massage|yoga|meditation|holistic/.test(industry)) key = "wellness";
  else if (/restaurant|food|cafe|bistro|dining/.test(industry)) key = "restaurant";
  else if (/medical|clinic|dental|health|doctor/.test(industry)) key = "medical";

  return GALLERY_TEMPLATES[key].map(({ seed, alt, category }) => ({
    src: `${PICSUM_BASE}/${seed}/800/600`,
    alt: `${alt} at ${business.name}`,
    category,
  }));
}

function buildJsonLd(business: BusinessData, ux: WebsiteBlueprint["ux"]): object {
  const addressParts = business.address.match(/^(.+),\s*(.+),\s*([A-Z]{2})\s+(\d{5})/);
  const streetAddress = addressParts ? addressParts[1].trim() : business.address;
  const locality = addressParts ? addressParts[2].trim() : business.location.split(",")[0];
  const region = addressParts ? addressParts[3] : "TX";
  const postalCode = addressParts ? addressParts[4] : "";

  return {
    "@context": "https://schema.org",
    "@type": "BeautySalon",
    name: business.name,
    description: business.description,
    telephone: business.phone,
    email: business.email,
    address: {
      "@type": "PostalAddress",
      streetAddress,
      addressLocality: locality,
      addressRegion: region,
      postalCode,
      addressCountry: "US",
    },
    openingHoursSpecification: buildOpeningHoursSpec(business.operatingHours),
    sameAs: Object.values(business.socialLinks),
    image: "/og-image.svg",
    priceRange: "$$",
    servesCuisine: undefined,
  };
}

function buildOpeningHoursSpec(hours: Record<string, string>): object[] {
  const DAY_MAP: Record<string, string[]> = {
    "Monday": ["Monday"],
    "Tuesday": ["Tuesday"],
    "Wednesday": ["Wednesday"],
    "Thursday": ["Thursday"],
    "Friday": ["Friday"],
    "Saturday": ["Saturday"],
    "Sunday": ["Sunday"],
    "Monday–Friday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "Monday-Friday": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    "Weekdays": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  };

  const specs: object[] = [];
  for (const [dayLabel, timeRange] of Object.entries(hours)) {
    if (dayLabel === "Note") continue;
    const days = DAY_MAP[dayLabel];
    if (!days) continue;
    const m = timeRange.match(/(\d+:\d+)\s*(AM|PM)\s*[–\-]\s*(\d+:\d+)\s*(AM|PM)/i);
    if (!m) continue;
    const opens = to24h(m[1], m[2]);
    const closes = to24h(m[3], m[4]);
    for (const day of days) {
      specs.push({ "@type": "OpeningHoursSpecification", dayOfWeek: `https://schema.org/${day}`, opens, closes });
    }
  }
  return specs;
}

function to24h(time: string, ampm: string): string {
  const [h, m] = time.split(":").map(Number);
  let hour = h;
  if (ampm.toUpperCase() === "PM" && hour !== 12) hour += 12;
  if (ampm.toUpperCase() === "AM" && hour === 12) hour = 0;
  return `${String(hour).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

function toPascalCase(str: string): string {
  return str.replace(/([-_][a-z])/gi, (s) => s.toUpperCase().replace(/[-_]/, "")).replace(/^./, (s) => s.toUpperCase());
}

function escapeTemplate(s: string): string {
  return s.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}
