/**
 * TypeScript interfaces for the Stitchfy website blueprint.
 * This is the single source of truth for all blueprint data structures.
 * The Zod schema in blueprint.schema.ts validates at runtime against these types.
 */

// ─── Project ─────────────────────────────────────────────────────────────────

export interface ProjectMeta {
  schemaVersion: string;
  generatedAt: string;
  sourceFile: string;
  frameworkVersion: string;
}

// ─── Business ────────────────────────────────────────────────────────────────

export interface BusinessData {
  name: string;
  industry: string;
  description: string;
  location: string;
  address: string;
  serviceAreas: string[];
  phone: string;
  email: string;
  operatingHours: Record<string, string>;
  socialLinks: Record<string, string>;
  booking: string;
  services: string[];
  complianceFlags: string[];
  missingInformation: string[];
}

// ─── Pages ───────────────────────────────────────────────────────────────────

export interface PageCTA {
  label: string;
  href: string;
}

export interface PageDefinition {
  id: string;
  path: string;
  title: string;
  purpose: string;
  sections: string[];
  primaryCTA: PageCTA | null;
  secondaryCTA: PageCTA | null;
  requiredContent: string[];
  componentHints: string[];
}

// ─── UX ──────────────────────────────────────────────────────────────────────

export interface ColorPalette {
  primary: string;
  secondary: string;
  accent: string;
  text: string;
  background: string;
  border: string;
}

export interface Typography {
  headingFont: string;
  bodyFont: string;
  scaleBase: string;
  headingWeight: string;
}

export interface NavItem {
  label: string;
  href: string;
  external?: boolean;
}

export interface HeaderConfig {
  sticky: boolean;
  showPhone: boolean;
  showCTA: boolean;
  ctaLabel: string;
  ctaHref: string;
}

export interface FooterConfig {
  columns: string[];
  showHours: boolean;
  showSocial: boolean;
  showAddress: boolean;
  legalNote: string;
}

// Machine-readable hero visual spec — bridges colorPalette to component rendering.
// Generated by UX Agent; consumed directly by the site generator.
export interface HeroStyle {
  backgroundType: "solid" | "gradient" | "image";
  backgroundColor?: string;   // hex — used when backgroundType is "solid"
  gradientFrom?: string;      // hex — light end of gradient
  gradientTo?: string;        // hex — dark/accent end of gradient
  textColor: string;          // hex — must pass contrast against the background
  overlayOpacity?: number;    // 0–1, only when backgroundType is "image"
}

export interface UXData {
  brandPersonality: string[];
  colorPalette: ColorPalette;
  typography: Typography;
  layoutGuidelines: string[];
  navigation: NavItem[];
  header: HeaderConfig;
  footer: FooterConfig;
  heroStyle: HeroStyle;       // visual spec for the Hero component — replaces prose componentHints
  homepageStrategy: string;
  componentStrategy: string[];
  responsiveBehavior: string[];
  contentHierarchy: string[];
}

// ─── SEO ─────────────────────────────────────────────────────────────────────

export interface PageMeta {
  pageId: string;
  title: string;
  description: string;
}

export interface SEOData {
  siteTitle: string;
  defaultMetaDescription: string;
  pageMeta: PageMeta[];
  h1Rules: string[];
  h2Rules: string[];
  localSeo: string[];
  structuredDataRecommendations: string[];
  openGraph: Record<string, string>;
  imageAltTextRequirements: string[];
  internalLinking: string[];
  indexabilityRules: string[];
}

// ─── Accessibility ────────────────────────────────────────────────────────────

export type ChecklistPriority = "must" | "should" | "nice-to-have";

export interface QACheckItem {
  rule: string;
  description: string;
  priority: ChecklistPriority;
}

export interface AccessibilityData {
  targetStandard: string;
  semanticHtmlRequirements: string[];
  landmarkRequirements: string[];
  keyboardNavigationRequirements: string[];
  colorContrastRequirements: string[];
  formLabelRequirements: string[];
  imageAltTextRequirements: string[];
  focusStateRequirements: string[];
  ariaGuidelines: string[];
  reducedMotionGuidelines: string[];
  qaChecklist: QACheckItem[];
}

// ─── Frontend ─────────────────────────────────────────────────────────────────

export interface ComponentMapEntry {
  component: string;
  usedIn: string[];
  props: string[];
}

export interface Route {
  path: string;
  pageId: string;
  file: string;
}

export interface FrontendData {
  framework: string;
  renderingMode: string;
  componentMap: ComponentMapEntry[];
  routes: Route[];
  assets: Record<string, string>;
  forms: Record<string, string>;
  externalIntegrations: string[];
  unsupportedFeatures: string[];
  implementationNotes: string[];
}

// ─── QA ──────────────────────────────────────────────────────────────────────

export interface QAData {
  expectedReports: string[];
  lighthouseTargets: Record<string, number>;
  accessibilityChecks: string[];
  seoChecks: string[];
  knownLimitations: string[];
}

// ─── Root Blueprint ───────────────────────────────────────────────────────────

export interface WebsiteBlueprint {
  project: ProjectMeta;
  business: BusinessData;
  pages: PageDefinition[];
  ux: UXData;
  seo: SEOData;
  accessibility: AccessibilityData;
  frontend: FrontendData;
  qa: QAData;
}
