/**
 * IntegrationExporter — converts a validated, vendor-neutral
 * IntegrationDefinition into implementation-oriented artifacts for a
 * specific technical target (Phase 5.5A). Deliberately NOT related to
 * IntegrationProvider (framework/providers/integrations/integration-provider.types.ts):
 * an Exporter generates files; a Provider (a future Phase 5.5B concern)
 * would execute/connect. Neither extends nor imports the other — see
 * framework/capabilities/integrations/exporters/README.md.
 */

import type { ArchitectureReference } from "../../../core/contracts/architecture-reference.js";
import type { ImplementationArtifact } from "../../../core/contracts/artifact.js";
import type {
  SecurityArchitecture,
  GovernancePlan,
} from "../../security-governance/schemas/security-governance.types.js";
import type { SystemInventoryItem } from "../../../discovery/systems/system-inventory.types.js";
import type { WorkflowDefinition } from "../../workflow-automation/schemas/workflow-automation.types.js";
import type { IntegrationDefinition } from "../schemas/integrations.types.js";

/**
 * Closed union so adding a future target (java, openapi, webhook-typescript,
 * aws-lambda, azure-function, a vendor-specific target, ...) is a type-level
 * change here plus a new registered exporter — never an open string.
 */
export type IntegrationExportTarget = "generic-rest-typescript";

export interface IntegrationExportContext {
  /** Consumed, never regenerated — see generic-rest-typescript.readiness.ts. */
  securityArchitecture?: SecurityArchitecture;
  /** Accepted for forward extensibility (matches the task's own contract sketch); not consumed by generic-rest-typescript today. */
  governancePlan?: GovernancePlan;
  systems: SystemInventoryItem[];
  workflows: WorkflowDefinition[];
  /** Reserved for a future exporter that needs to know the write target ahead of time; the shipped exporter only ever produces paths relative to outputDir, written by the existing generic artifact-writer — unused today. */
  outputDirectory?: string;
}

export type ExportReadinessStatus = "ready" | "needs-review" | "blocked" | "unsupported";

/**
 * Distinct from the 2-value `severity: "error"|"warning"` used by every
 * validator in this codebase (integration-definition.validator.ts,
 * security-architecture.validator.ts, ...): readiness reasons need an
 * "info" tier for advisory notes (e.g. "base URL not supplied") that must
 * never affect `status` — conflating it into "warning" would make every
 * readiness reason look status-affecting when most aren't.
 */
export interface ExportReadinessReason {
  code: string;
  description: string;
  severity: "info" | "warning" | "blocking";
  architectureRefs: ArchitectureReference[];
}

export interface ExportReadiness {
  integrationId: string;
  exporterId: string;
  status: ExportReadinessStatus;
  reasons: ExportReadinessReason[];
  informationGapIds: string[];
  securityRequirementIds: string[];
  riskIds: string[];
}

export type GeneratedSourceFileLanguage = "typescript" | "json" | "markdown" | "yaml" | "text";
export type GeneratedSourceFileRole = "client" | "types" | "configuration" | "manifest" | "documentation" | "test";

/**
 * The persisted shape (as stored on IntegrationsSection.exports) carries no
 * `content` — the same text lives in the parallel ImplementationArtifact
 * (IntegrationExportBundle.artifacts, which is the SAME array pushed onto
 * IntegrationsSection.artifacts) so nothing generated by this phase is
 * duplicated in the written solution-blueprint.v1.json beyond the one
 * unavoidable place ImplementationArtifact.content already lives — the same
 * precedent integration-artifact.generator.ts already sets by JSON-stringifying
 * the full IntegrationDefinition into a `.integration.json` artifact.
 */
export interface GeneratedSourceFile {
  path: string;
  language: GeneratedSourceFileLanguage;
  role: GeneratedSourceFileRole;
}

export interface IntegrationExportBundle {
  id: string;
  integrationId: string;
  exporterId: string;
  readiness: ExportReadiness;
  files: GeneratedSourceFile[];
  artifacts: ImplementationArtifact[];
  notes: string[];
}

export interface IntegrationExportManifest {
  schemaVersion: "1.0";
  integrationId: string;
  integrationVersion: string;
  exporterId: string;
  exporterVersion: string;
  readiness: ExportReadinessStatus;
  generatedFiles: string[];
  operationIds: string[];
  dataContractIds: string[];
  securityRequirementIds: string[];
  riskIds: string[];
  informationGapIds: string[];
  generatedAt: string;
}

export interface IntegrationExporter<TOptions = unknown, TResult = IntegrationExportBundle> {
  id: string;
  name: string;
  version: string;
  target: IntegrationExportTarget;

  /** Source of truth is the validated IntegrationDefinition itself — never system name or SaaS classification (task item 9). */
  supports(integration: IntegrationDefinition): boolean;

  assessReadiness(integration: IntegrationDefinition, context: IntegrationExportContext): ExportReadiness;

  export(integration: IntegrationDefinition, context: IntegrationExportContext, options?: TOptions): Promise<TResult>;
}
